-- DT VIP — bảng lưu lịch sử game theo HASH IP.
-- Không lưu IP thô.

create table if not exists public.ip_game_usage (
  id bigint generated by default as identity primary key,
  ip_hash text not null,
  game_id text not null,
  first_seen timestamptz not null default now(),
  last_seen timestamptz not null default now(),
  constraint ip_game_usage_unique unique (ip_hash, game_id)
);

create index if not exists ip_game_usage_ip_hash_idx
  on public.ip_game_usage (ip_hash);

alter table public.ip_game_usage enable row level security;

-- Dự án Supabase mới từ 2026 có thể không tự grant Data API.
grant usage on schema public to service_role;
grant select, insert, update on table public.ip_game_usage to service_role;
grant usage, select on sequence public.ip_game_usage_id_seq to service_role;

-- Không tạo policy công khai. Chỉ backend dùng secret key/service_role mới đọc/ghi được.
